CafeAnything.Web/Models/Users.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace CafeAnything.Web.Models
{
    public class Users
    {
        [Key]
        public int ID { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public Roles Roles { get; set; }

        public virtual ICollection<Tables> Tables { get; set; }
    }

    public enum Roles
    {
        Admin,Customer,Cashier
    }
}

CafeAnything.Web/Controllers/AdminsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using CafeAnything.DomainModel;
using CafeAnything.Persistence;
using CafeAnything.Persistence.Repositories;
//using CafeAnything.Web.Models;
using Scrypt;

namespace CafeAnything.Web.Controllers
{
    public class AdminsController : Controller
    {
        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        // Grab Database from repositories

        private UsersRepository AllUsers = new UsersRepository();
        private CashierRepository Table = new CashierRepository();
        private OrderCartRepository OrderCart = new OrderCartRepository();
        private CategoryRepository Category = new CategoryRepository();

        /////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

        // User Methods

        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(Users user)
        {
            // Note : Username and Password are same
            ScryptEncoder encoder = new ScryptEncoder();

            // Find the user valid or not, and also check the role is admin or not
            var acc = AllUsers.CheckUser(user.Username, Roles.Admin);

            if (acc != null)
            {
                bool areEquals = false;
                // Compare what u typed with the hashed password which are saved inside the database
                areEquals = encoder.Compare(user.Password, acc.Password);

                // Check the password correct or not
                if (areEquals != false)
                {
                    // After Login, i created two session to store id and username
                    Session["AdminID"] = acc.ID;
                    Session["Username"] = acc.Username;
                    return RedirectToAction("Users");
                }
                else
                {
                    ViewbagError("Invalid Username or Password");
                }
                return View();
            }
            else
            {
                ViewbagError("Invalid Username or Password");
            }
            return View();
        }

        public ActionResult Users()
        {
            // After login , if your user list is empty, thn it will show this error msg
            if (AllUsers.GetUsers().Count() == 0)
            {
                ViewbagError("No have data");
                return View();
            }
            return View(AllUsers.GetUsers());
        }

        public ActionResult CreateNewAcc()
        {
            return View();
        }

        [HttpPost]
        public ActionResult CreateNewAcc([Bind(Include = "ID , Username , Password , Roles")] Users user)
        {
            ScryptEncoder encoder = new ScryptEncoder();

            if (ModelState.IsValid)
            {
                try
                {
                    // hash the password
                    user.Password = encoder.Encode(user.Password);

                    CheckUserName(user.Username);

                    ViewbagSuccess("New User Created Successful.");
                    AllUsers.AddUser(user);
                    return View();
                }
                catch (Exception error)
                {
                    ViewbagError(error.Message);
                }
            }
            return View();
        }

        public ActionResult UserDetail(int? id)
        {
            // Find the user valid or not
            Users users = AllUsers.GetUser(id);
            if (users == null)
            {
                return RedirectToAction("Users");
            }
            return View(users);
        }

        public ActionResult DeleteUser(int? id)
        {
            // Find the user valid or not
            Users users = AllUsers.GetUser(id);
            if (users == null)
            {
                return RedirectToAction("Users");
            }
            // These ViewBag just for checking which user u selected to delete
            ViewBag.CheckRoles = users.Roles;

            ViewBag.CustomerRole = Roles.Customer;
            ViewBag.AdminRole = Roles.Admin;
            ViewBag.CashierRole = Roles.Cashier;
            return View(users);
        }

        [HttpPost, ActionName("DeleteUser")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteUserConfirmed(int id)
        {

            // If selected user is admin or cashier, it will show different msg, you can go to the view and see the if statement
            var checkAdmin = AllUsers.GetUsers().Where(c => c.ID == id && (c.Roles == Roles.Admin || c.Roles == Roles.Cashier)).SingleOrDefault();

            var checkCustomer = AllUsers.GetUsers().Where(c => c.ID == id && c.Roles == Roles.Customer).SingleOrDefault();

            if (checkAdmin != null)
            {
                AllUsers.RemoveUser(checkAdmin);
            }
            else if (checkCustomer != null)
            {
                // Find which table is reserved by this checkCustomer
                var checkTable = Table.GetTables().Where(c => c.ID == checkCustomer.ID).SingleOrDefault();

                if (checkTable != null)
                {
                    // Check which order in this table
                    var checkOrder = OrderCart.GetOrderCarts().Where(c => c.TablesID == checkTable.TablesID).ToList();

                    OrderCart.RemoveRangeOrderCart(checkOrder);
                    checkTable.TotalQuantity = 0;
                    checkTable.TotalAmount = 0;
                    checkTable.TStatus = TStatus.Empty;
                    checkTable.ID = null;
                    Table.UpdateTable(checkTable);
                    AllUsers.RemoveUser(checkCustomer);
                }
                else
                {
                    AllUsers.RemoveUser(checkCustomer);
                }
            }
            return RedirectToAction("Users");
        }

        public ActionResult EditUser(int? id)
        {
            // Find the user valid or not
            Users user = AllUsers.GetUser(id);
            if (user != null)
            {
                return View(user);
            }
            return RedirectToAction("Users");
        }

        [HttpPost]
        public ActionResult EditUser([Bind(Include = "ID , Username , Roles")] Users user)
        {
            // Get the selected user after you click the edit
            var EditUser = AllUsers.GetUsers().Where(c => c.ID == user.ID).SingleOrDefault();

            // Get other user that the username is not same as selected user name from the Users database
            var FilterUser = AllUsers.GetUsers().Where(c => c.Username != EditUser.Username).ToList();

            // Check the users name got same as what u typed got duplicate or not
            var CheckDuplicate = FilterUser.Where(c => c.Username == user.Username).SingleOrDefault();

            if (ModelState.IsValid)
            {
                try
                {
                    if (CheckDuplicate != null)
                    {
                        throw new Exception("Username Duplicate");
                    }
                    EditUser.Username = user.Username;
                    EditUser.Roles = user.Roles;
                    ViewbagSuccess("Edit User Successful.");
                    AllUsers.UpdateUser(EditUser);
                    return View(EditUser);
                }
                catch (Exception lol)
                {
                    ViewbagError(lol.Message);
                }
            }
            return View(EditUser);
        }

        public ActionResult Logout()
        {
            return View();
        }

        public ActionResult LogoutPage()
        {
            return View();
        }

        public ActionResult AjaxCreateUser(string Username, Roles Roles)
        {
            // check user after you type the username
            var CheckDuplicate = AllUsers.GetUsers().Where(c => c.Username == Username && c.Roles == Roles).SingleOrDefault();

            if (CheckDuplicate != null)
            {
                var usernameDuplicate = "Username Duplicate";
                return Json(new { Error = true, usernameDuplicate }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Error = false }, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AjaxEditUser(int ID, string Username, Roles Roles)
        {
            // Get the selected user after you click the edit
            var EditUser = AllUsers.GetUsers().Where(c => c.ID == ID).SingleOrDefault();

            // Get other user that the username is not same as selected user name and the role from the Users database
            var FilterUser = AllUsers.GetUsers().Where(c => c.Username != EditUser.Username && c.Roles == Roles).ToList();

            // Check the users name got same as what u typed got duplicate or not
            var CheckDuplicate = FilterUser.Where(c => c.Username == Username).SingleOrDefault();

            if (CheckDuplicate != null)
            {
                var usernameDuplicate = "Username Duplicate";
                return Json(new { Error = true, usernameDuplicate }, JsonRequestBehavior.AllowGet);
            }
            else
            {
                return Json(new { Error = false }, JsonRequestBehavior.AllowGet);
            }
        }

        [NonAction]
        public string CheckUserName(string Username)
        {
            // Check the user database got duplicate name or not
            var checkDuplicate = AllUsers.GetUsers().Where(c => c.Username == Username).SingleOrDefault();

CafeAnything.Web/Views/Admins/CategoryDetail.cshtml
@model CafeAnything.DomainModel.Categories

@{
    ViewBag.Title = "Category Details";
    Layout = "~/Views/AdminLayout/AdminHomeLayout.cshtml";
}

<div>
    <h2>Category Details</h2>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FoodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FoodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
           RM @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FoodImg)
        </dt>

        <dd>
            @{
                var base64 = Convert.ToBase64String(Model.FoodImg);
                var imgsrc = string.Format("data:image/gif;base64,{0}", base64);
            }
            <img src="@imgsrc" style="max-height : 280px ; max-width:250px;" />
        </dd>

    </dl>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            @Html.ActionLink(" Menu Page", "CategoryMenu", "Admins", new { @class = "btn btn-primary btn-sm w3-button w3-aqua w3-round-xlarge w3-border-red glyphicon glyphicon-home" })
        </div>
    </div>

</div>

CafeAnything.Web/Views/Admins/CreateCategory.cshtml
@model CafeAnything.DomainModel.Categories

@{
    ViewBag.Title = "Create Category";
    Layout = "~/Views/AdminLayout/AdminHomeLayout.cshtml";
}

<h2>Create New Category</h2>

@using (Html.BeginForm("CreateCategory", "Admins", FormMethod.Post , new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <hr />
        <div class="form-group">
            @Html.LabelFor(model => model.CategoryType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.CategoryType, htmlAttributes: new { @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small" })
                @Html.ValidationMessageFor(model => model.CategoryType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FoodName, new { htmlAttributes = new {required="required", @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small" } })
                @Html.ValidationMessageFor(model => model.FoodName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new {step="0.01" , required="required" , placeholder="RM ", type = "number", @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="UserPhoto" id="UserPhoto" accept="image/*" onchange="return upload_image()" class="form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small" required />
                @{
                    if (ViewBag.ImgError != null)
                    {
                        <p class="alert alert-danger text-center">@ViewBag.ImgError</p>
                    }
                }
                <br />
                <div id="before_upload">
                    <img src="~/Content/IMG/Default.png" width="280" height="150" />
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.TextBox("CreateCategory", "Create Category", new { type = "submit", @class = "w3-btn w3-white w3-border w3-border-red w3-round-large test" })
            </div>
        </div>

        <div class="text-danger" id="errorMsg">
            @{
                if (ViewBag.Error != null)
                {
                    <p class="alert alert-danger text-center">@ViewBag.Error</p>
                }
            }
        </div>

        <div style="background-color:#00ff00">
            @{
                if (ViewBag.Success != null)
                {
                    <p class="text-center">@ViewBag.Success</p>
                }
            }
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink(" Menu Page", "CategoryMenu", "Admins", new { @class = "btn btn-primary btn-sm w3-button w3-aqua w3-round-xlarge w3-border-red glyphicon glyphicon-home" })
            </div>
        </div>
    </div>
}

<script>
    function upload_image() {
        var SelectedFile = document.getElementById("UserPhoto");
        var filePatch = SelectedFile.value;
        var allowedExtension = /(\.jpg|\.jpeg|\.png)$/i;
        if (!allowedExtension.exec(filePatch)) {
            alert('Only accept jpg,png,jpeg. Please upload again.');
            SelectedFile.value = "";
            var image = $("#before_upload")
            image.fadeOut('fast', function () {
                image.html('<img src="~/Content/IMG/Default.png" style="width:30%/>');
                image.fadeIn('fast');
            });
        }
        else {
            if (SelectedFile.files && SelectedFile.files[0]) {
                var reader = new FileReader();
                reader.onload = function (event) {
                    var image = $("#before_upload")
                    image.fadeOut('fast', function () {
                        image.html('<img src="' + event.target.result + '" style="width:30%"/>');
                        image.fadeIn('fast');
                    });
                };
                reader.readAsDataURL(SelectedFile.files[0]);
            }
        }
    }
</script>

CafeAnything.Web/Views/Admins/CreateNewAcc.cshtml
@model CafeAnything.DomainModel.Users

@{
    ViewBag.Title = "Create User";
    Layout = "~/Views/AdminLayout/AdminHomeLayout.cshtml";
}

<h2>Create New User</h2>


@using (Html.BeginForm("CreateNewAcc", "Admins", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Username, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Username, new { htmlAttributes = new { @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small", required = "required" } })
                @Html.ValidationMessageFor(model => model.Username, "", new { @class = "text-danger" })
            </div>
        </div>
        <div id="usernameDuplicate"></div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { type = "password", @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small", required = "required" } })
                <span onclick="ShowPass()" class="glyphicon glyphicon-eye-open"></span>
                <br />
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Roles, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.Roles, htmlAttributes: new { @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small" })
                @Html.ValidationMessageFor(model => model.Roles, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.TextBox("CreateAcc", "Create Acc", new { type = "submit", @class = "w3-btn w3-white w3-border w3-border-red w3-round-large test" })
            </div>
        </div>

        <div class="text-danger" id="errorMsg">
            @{
                if (ViewBag.Error != null)
                {
                    <p class="alert alert-danger text-center">@ViewBag.Error</p>
                }
            }
        </div>

        <div style="background-color:#00ff00">
            @{
                if (ViewBag.Success != null)
                {
                    <p class="text-center">@ViewBag.Success</p>
                }
            }
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink(" User Page", "Users", "Admins", new { @class = "btn btn-primary btn-sm w3-button w3-aqua w3-round-xlarge w3-border-red glyphicon glyphicon-home" })
            </div>
        </div>
    </div>
}

<script language="javascript" type="text/javascript">

    $(function () {

        $("#Username").keyup(function () {
            var username = $("#Username").val();
            var roles = $("#Roles").val();
            $.ajax({
                type: "POST",
                url: "/Admins/AjaxCreateUser",
                data: {
                    Username: username,
                    Roles: roles
                },
                success: function (response) {
                    if (response.Error == true) {
                        $("#usernameDuplicate").attr('class', 'alert alert-danger text-center').html(response.usernameDuplicate);
                        $(".test").attr("disabled", true);
                    }
                    else if (response.Error == false) {
                        $("#usernameDuplicate").attr('class', '').html("");
                        $(".test").attr("disabled", false);
                    }
                }
            })
        })

        $("#Roles").click(function () {
            var username = $("#Username").val();
            var roles = $("#Roles").val();
            $.ajax({
                type: "POST",
                url: "/Admins/AjaxCreateUser",
                data: {
                    Username: username,
                    Roles: roles
                },
                success: function (response) {
                    if (response.Error == true) {
                        $("#usernameDuplicate").attr('class', 'alert alert-danger text-center').html(response.usernameDuplicate);
                        $(".test").attr("disabled", true);
                    }
                    else if (response.Error == false) {
                        $("#usernameDuplicate").attr('class', '').html("");
                        $(".test").attr("disabled", false);
                    }
                }
            })
        })
    })

    function ShowPass() {
        var x = document.getElementById('Password');

        if (x.type === "password") {
            x.type = "text";
        }
        else {
            x.type = "password";
        }
    }

</script>

CafeAnything.Web/Views/Admins/DeleteCategory.cshtml
@model CafeAnything.DomainModel.Categories

@{
    ViewBag.Title = "Delete Category";
    Layout = "~/Views/AdminLayout/AdminHomeLayout.cshtml";
}

<div class="jumbotron">

    <h2 style="color:red">Are you sure you want to delete this?</h2>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.CategoryType)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.CategoryType)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FoodName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FoodName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
           RM @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FoodImg)
        </dt>

        <dd>
            @{
                var base64 = Convert.ToBase64String(Model.FoodImg);
                var imgsrc = string.Format("data:image/gif;base64,{0}", base64);
            }
            <img src="@imgsrc" style="max-height : 280px ; max-width:250px;" />
        </dd>

    </dl>

    <p class="alert alert-danger"><strong>Note : </strong>Selected Category which Customer Ordered will be deleted.</p>

    @using (Html.BeginForm("DeleteCategory", "Admins", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.TextBox("Delete", "Delete Category", new { type = "submit", @class = "w3-btn w3-white w3-border w3-border-red w3-round-large" }) |
                @Html.ActionLink(" Menu Page", "CategoryMenu", "Admins", new { @class = "btn btn-primary btn-sm w3-button w3-aqua w3-round-xlarge w3-border-red glyphicon glyphicon-home" })
            </div>
        </div>
    }
</div>

CafeAnything.Web/Views/Admins/DeleteUser.cshtml
@model CafeAnything.DomainModel.Users

@{
    ViewBag.Title = "Delete User";
    Layout = "~/Views/AdminLayout/AdminHomeLayout.cshtml";
}

<div class="jumbotron">

    <h2 style="color:red">Are you sure you want to delete this?</h2>
    <br />

    <div>
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Username)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Username)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Roles)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Roles)
            </dd>

        </dl>

        @if (ViewBag.CheckRoles == ViewBag.CustomerRole)
        {
            <p class="alert alert-danger"><strong>Note : </strong>Selected User which Order will be deleted.</p>
        }

        @if (ViewBag.CheckRoles == ViewBag.AdminRole || ViewBag.CheckRoles == ViewBag.CashierRole)
        {
            <p class="alert alert-danger"><strong>Note : </strong>Selected User will be deleted.</p>
        }

        @using (Html.BeginForm("DeleteUser", "Admins", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    @Html.TextBox("Delete", "Delete User", new { type = "submit", @class = "w3-btn w3-white w3-border w3-border-red w3-round-large" }) |
                    @Html.ActionLink(" Users Page", "Users", "Admins", new { @class = "btn btn-primary btn-sm w3-button w3-aqua w3-round-xlarge w3-border-red glyphicon glyphicon-home" })
                </div>
            </div>
        }
    </div>
</div>

CafeAnything.Web/Views/Admins/EditCategory.cshtml
@model CafeAnything.DomainModel.Categories

@{
    ViewBag.Title = "Edit Category";
    Layout = "~/Views/AdminLayout/AdminHomeLayout.cshtml";
}

<h2>Edit Category</h2>

@using (Html.BeginForm("EditCategory", "Admins", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CategoryID, new { @readonly = "readonly" })

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EnumDropDownListFor(model => model.CategoryType, htmlAttributes: new { @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small" })
                @Html.ValidationMessageFor(model => model.CategoryType, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FoodName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FoodName, new { htmlAttributes = new { @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small" } })
                @Html.ValidationMessageFor(model => model.FoodName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { step="0.01" , type = "number", @class = "form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>
        
        <div class="form-group">
            @Html.LabelFor(model => model.FoodImg, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="UserPhoto" id="UserPhoto" accept="image/*" onchange="return upload_image()" class="form-control w3-btn w3-white w3-border w3-border-red w3-round-large w3-padding-small" />
                <br />
                <div id="before_upload">
                    @{
                        var base64 = Convert.ToBase64String(Model.FoodImg);
                        var imgsrc = string.Format("data:image/gif;base64,{0}", base64);
                    }
                    <img src="@imgsrc" style="max-height : 280px ; max-width:250px;" />
                </div>
            </div>
        </div>

        <div style="background-color:#00ff00">
            @{
                if (ViewBag.Success != null)
                {
                    <p class="text-center">@ViewBag.Success</p>
                }
            }
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.TextBox("Save", "Save Changes", new { type = "submit", @class = "w3-btn w3-white w3-border w3-border-red w3-round-large test" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.ActionLink(" Menu Page", "CategoryMenu", "Admins", new { @class = "btn btn-primary btn-sm w3-button w3-aqua w3-round-xlarge w3-border-red glyphicon glyphicon-home" })
            </div>
        </div>
    </div>
}

<script>
    function upload_image() {
        var SelectedFile = document.getElementById("UserPhoto");
        var filePatch = SelectedFile.value;
        var allowedExtension = /(\.jpg|\.jpeg|\.png)$/i;
        if (!allowedExtension.exec(filePatch)) {
            alert('Only accept jpg,png,jpeg. Please upload again.');
            SelectedFile.value = "";
            var image = $("#before_upload")
            image.fadeOut('fast', function () {
                image.html('<img src="~/Content/IMG/Default.png" style="width:30%/>');
                image.fadeIn('fast');
            });
        }
        else {
            if (SelectedFile.files && SelectedFile.files[0]) {
                var reader = new FileReader();
                reader.onload = function (event) {
                    var image = $("#before_upload")
                    image.fadeOut('fast', function () {
                        image.html('<img src="' + event.target.result + '" style="width:30%"/>');
                        image.fadeIn('fast');
                    });
                };
                reader.readAsDataURL(SelectedFile.files[0]);
            }
        }
    }
</script>

CafeAnything.Web/Views/Admins/Logout.cshtml
@{
    ViewBag.Title = "Logout";
    Layout = "~/Views/AdminLayout/AdminLoginLayout.cshtml";

    if (Session["AdminID"] == null)
    {
        Layout = null;
        Response.Redirect("/Admins/Login");
    }
}

@{
    Response.Redirect("/Admins/LogoutPage");
}